### ISSUE TITLE
Module not found: Error: Can't resolve './html4-entities' in './node_modules/native-url/dist'

### ISSUE THREAD

**Issue by martsie** [shackijj/widget-typescript#3] opened 2020-08-05 04:37 UTC
Using preact cli along with widget-typescript results in the following errors when running `yarn run dev`

```
✖ ERROR ../node_modules/native-url/dist/index.mjs
Module not found: Error: Can't resolve './html4-entities' in './node_modules/native-url/dist'
 @ ../node_modules/native-url/dist/index.mjs 11:23-50
 @ ../node_modules/webpack-dev-server/client/utils/createSocketUrl.js
 @ ../node_modules/webpack-dev-server/client?http://0.0.0.0:8090
 @ multi ../node_modules/webpack-dev-server/client?http://0.0.0.0:8090 ../node_modules/webpack/hot/dev-server.js ../node_modules/preact-cli/lib/lib/entry webpack-dev-server/client webpack/hot/dev-server
✖ ERROR ../node_modules/native-url/dist/index.mjs
Module not found: Error: Can't resolve './html5-entities' in './node_modules/native-url/dist'
 @ ../node_modules/native-url/dist/index.mjs 15:23-50
 @ ../node_modules/webpack-dev-server/client/utils/createSocketUrl.js
 @ ../node_modules/webpack-dev-server/client?http://0.0.0.0:8090
 @ multi ../node_modules/webpack-dev-server/client?http://0.0.0.0:8090 ../node_modules/webpack/hot/dev-server.js ../node_modules/preact-cli/lib/lib/entry webpack-dev-server/client webpack/hot/dev-server
✖ ERROR ../node_modules/native-url/dist/index.mjs
Module not found: Error: Can't resolve './xml-entities' in './node_modules/native-url/dist'
 @ ../node_modules/native-url/dist/index.mjs 7:21-46
 @ ../node_modules/webpack-dev-server/client/utils/createSocketUrl.js
 @ ../node_modules/webpack-dev-server/client?http://0.0.0.0:8090
 @ multi ../node_modules/webpack-dev-server/client?http://0.0.0.0:8090 ../node_modules/webpack/hot/dev-server.js ../node_modules/preact-cli/lib/lib/entry webpack-dev-server/client webpack/hot/dev-server
```

I've tried googling around but haven't found anything about this error. Anybody else hit this?

**Comment by prateekbh** [comment] 2020-08-05 19:11
can you check if `native-url` is present in node_modules?

**Comment by martsie** [comment] 2020-08-06 04:29
Yep, native-url is present. I'm running node 10.15. My fix is to remove the native-url index.mjs file so that the js file is used instead which doesn't seem to cause the error.

You can put this line in package.json scripts section if you want widget-typescript to work.
```
"postinstall": "rm ./node_modules/native-url/dist/index.mjs"
```

**Comment by rschristian** [comment] 2022-12-28 10:46
Going to close this out, can't reproduce. Might've been fixed at some point.

**Closed as not planned by rschristian** 2022-12-28 10:46 UTC
